In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('../../data/raw/housing-infomation.csv')
df

,ข้อมูลที่อยู่อาศัยสร้างเสร็จจดทะเบียน เดือน พฤษภาคม 2569,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,การแสดงผลจังหวัด แยกตามอำเภอ (กรุงเทพมหานคร),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ลำดับที่,จังหวัด/อำเภอ,บ้าน (1),โรงแรม (7),โรงงาน (13),หอพัก (14),ตึกแถว (16),ห้องแถว (17),ตึก (18),ร้านค้า (19),...,ห้างหุ้นส่วนจำกัด (33),ห้างหุ้นส่วนนิติบุคคล (34),โกดัง (37),บริษัท (38),ทาวน์เฮ้าส์ (39),บ้านแฝด (45),บ้านแถว (49),ทาวน์โฮม (51),อื่น ๆ,รวม
4,NaN,รวม,"1,969,244","1,778",656,"2,193","52,671","1,057","106,609","12,488",...,23,5,792,558,"101,000","22,662","38,586",765,"107,746","3,373,689"
5,NaN,กรุงเทพมหานคร,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,ท้องถิ่นเขตพระนคร,"16,602",116,0,2,11,0,16,775,...,0,0,0,1,0,0,0,0,697,"18,771"
7,2,ท้องถิ่นเขตดุสิต,"19,570",4,9,6,110,21,431,4,...,0,0,0,1,23,0,0,0,"9,175","34,408"
8,3,ท้องถิ่นเขตหนองจอก,"53,799",1,23,12,774,0,"12,090",250,...,0,0,52,8,"3,154","2,079",506,0,"1,993","76,434"
9,4,ท้องถิ่นเขตบางรัก,"20,250",112,0,4,369,17,"5,236",48,...,0,0,0,0,0,0,0,0,361,"36,130"
10,5,ท้องถิ่นเขตบางเขน,"63,197",71,3,123,"2,423",2,776,837,...,0,0,10,0,"6,415",778,263,0,"13,467","121,263"
11,6,ท้องถิ่นเขตบางกะปิ,"44,794",62,5,0,"4,575",11,"17,104",142,...,0,0,12,0,651,200,896,0,"1,465","119,442"
12,7,ท้องถิ่นเขตปทุมวัน,"14,942",68,1,2,634,20,"4,645",321,...,0,0,0,0,0,2,0,0,707,"32,588"
13,8,ท้องถิ่นเขตป้อมปราบศัตรูพ่าย,"16,693",9,1,2,428,11,53,610,...,0,0,1,3,0,0,0,0,462,"19,644"
14,9,ท้องถิ่นเขตพระโขนง,"20,283",22,29,91,"2,521",9,773,167,...,7,0,13,58,"3,718",83,62,0,"1,360","66,661"
15,10,ท้องถิ่นเขตมีนบุรี,"54,386",15,59,7,732,5,346,32,...,0,2,7,9,"2,374",56,0,0,"1,344","68,688"
16,11,ท้องถิ่นเขตลาดกระบัง,"59,372",29,77,55,460,2,869,299,...,0,0,223,7,"7,797",726,777,84,"3,688","109,969"
17,12,ท้องถิ่นเขตยานนาวา,"31,355",4,7,38,81,33,26,57,...,0,0,37,2,364,80,0,94,"1,028","54,938"
18,13,ท้องถิ่นเขตสัมพันธวงศ์,"11,992",17,0,1,110,1,85,121,...,0,0,0,4,0,0,1,0,153,"12,947"
19,14,ท้องถิ่นเขตพญาไท,"23,675",32,0,13,83,0,286,104,...,0,0,0,10,76,2,0,0,"2,383","47,727"
20,15,ท้องถิ่นเขตธนบุรี,"36,996",6,1,2,"1,465",265,"2,195",62,...,0,0,1,0,19,6,30,0,654,"66,178"
21,16,ท้องถิ่นเขตบางกอกใหญ่,"24,063",10,3,6,236,1,197,20,...,0,0,0,0,244,6,0,0,201,"33,222"
22,17,ท้องถิ่นเขตห้วยขวาง,"48,313",62,1,2,292,0,94,384,...,0,1,3,11,219,96,145,0,"2,535","97,252"
23,18,ท้องถิ่นเขตคลองสาน,"27,296",33,0,6,180,0,110,22,...,0,0,0,0,0,0,0,0,400,"44,647"
24,19,ท้องถิ่นเขตตลิ่งชัน,"38,671",1,2,4,109,1,228,414,...,1,0,5,1,67,64,154,0,"1,780","45,601"
25,20,ท้องถิ่นเขตบางกอกน้อย,"41,979",20,0,35,913,79,112,47,...,0,0,1,0,0,120,364,0,"1,666","57,863"
26,21,ท้องถิ่นเขตบางขุนเทียน,"59,751",6,24,218,"5,627",5,774,383,...,0,0,248,0,"11,078",716,0,82,"2,598","96,674"
27,22,ท้องถิ่นเขตภาษีเจริญ,"39,380",26,0,14,677,11,286,12,...,3,0,0,0,"3,427",173,347,0,884,"70,434"
28,23,ท้องถิ่นเขตหนองแขม,"51,948",1,17,13,688,163,138,45,...,0,0,7,20,"7,105","2,026",34,358,"1,650","66,880"
29,24,ท้องถิ่นเขตราษฎร์บูรณะ,"30,464",9,3,14,258,57,"1,242",80,...,0,0,2,3,294,288,"1,390",0,"2,432","41,022"
30,25,ท้องถิ่นเขตบางพลัด,"38,952",28,31,7,207,13,328,31,...,0,0,0,0,5,4,9,0,"1,042","62,310"
31,26,ท้องถิ่นเขตดินแดง,"34,037",67,6,11,"1,946",10,"2,954",187,...,0,0,1,4,164,16,0,0,"1,154","66,712"
32,27,ท้องถิ่นเขตบึงกุ่ม,"44,715",8,3,6,"2,144",8,"8,805",24,...,0,0,4,2,877,391,729,0,"1,571","80,450"
33,28,ท้องถิ่นเขตสาทร,"28,176",59,4,4,84,3,757,37,...,0,0,2,0,1,0,3,0,"1,940","45,286"
34,29,ท้องถิ่นเขตบางซื่อ,"39,222",1,3,116,545,7,243,225,...,0,0,5,1,370,2,7,0,"2,717","79,322"
35,30,ท้องถิ่นเขตจตุจักร,"59,920",54,2,477,"1,215",0,27,969,...,0,0,0,2,41,179,747,0,"2,528","143,255"
36,31,ท้องถิ่นเขตบางคอแหลม,"30,412",8,2,16,320,0,"1,397",26,...,0,0,0,0,25,6,29,0,666,"41,122"
37,32,ท้องถิ่นเขตประเวศ,"50,899",27,12,25,"1,848",22,"1,694",102,...,6,0,15,285,"5,226","2,242","7,629",0,"3,471","108,495"
38,33,ท้องถิ่นเขตคลองเตย,"43,047",130,22,15,203,5,158,28,...,0,0,0,0,1,2,0,0,"3,034","83,912"
39,34,ท้องถิ่นเขตสวนหลวง,"31,992",16,2,11,898,12,"17,896",29,...,0,0,0,2,481,555,"3,410",22,765,"89,633"
40,35,ท้องถิ่นเขตจอมทอง,"59,775",5,6,10,490,6,324,63,...,0,2,11,10,490,167,"1,420",0,"1,308","74,988"
41,36,ท้องถิ่นเขตดอนเมือง,"48,232",14,4,64,949,4,297,53,...,0,0,0,6,"11,257","1,787",4,15,"2,089","84,166"
42,37,ท้องถิ่นเขตราชเทวี,"22,824",235,0,108,"1,380",17,"1,586","2,248",...,0,0,3,0,0,2,0,0,"3,355","58,118"
43,38,ท้องถิ่นเขตลาดพร้าว,"43,189",54,0,0,929,1,431,77,...,0,0,6,5,"2,058",321,169,0,"1,247","60,963"
44,39,ท้องถิ่นเขตวัฒนา,"39,092",210,2,13,486,13,990,196,...,0,0,0,1,27,0,0,0,612,"88,103"
45,40,ท้องถิ่นเขตบางแค,"83,579",4,4,32,253,4,649,86,...,0,0,3,0,"5,084",416,"1,391",0,788,"100,335"
46,41,ท้องถิ่นเขตหลักสี่,"32,758",26,16,111,"1,113",22,38,132,...,1,0,11,40,"1,127",371,989,0,"6,413","63,342"
47,42,ท้องถิ่นเขตสายไหม,"66,335",2,1,117,"5,115",64,"6,504",99,...,0,0,1,4,"5,785","1,529","7,507",12,"6,680","113,268"
48,43,ท้องถิ่นเขตคันนายาว,"26,376",9,16,102,"1,746",5,"2,882",224,...,1,0,0,15,"2,019",362,985,0,956,"49,594"
49,44,ท้องถิ่นเขตสะพานสูง,"31,255",4,2,14,"1,176",7,"1,700",36,...,2,0,20,10,"2,530","1,024","4,475",0,775,"44,941"
50,45,ท้องถิ่นเขตวังทองหลาง,"45,498",25,2,1,"2,233",2,"2,924",131,...,0,0,1,9,214,315,764,0,944,"66,667"
51,46,ท้องถิ่นเขตคลองสามวา,"72,043",1,18,17,"1,277",56,149,"1,394",...,0,0,18,10,"6,597","4,018","2,913",20,"5,291","95,430"
52,47,ท้องถิ่นเขตบางนา,"29,688",55,202,43,396,18,693,161,...,0,0,20,1,251,29,44,0,"1,507","83,304"
53,48,ท้องถิ่นเขตทวีวัฒนา,"33,910",0,3,43,134,0,"1,284",443,...,0,0,6,0,437,361,0,0,976,"37,687"
54,49,ท้องถิ่นเขตทุ่งครุ,"36,605",0,24,136,"1,080",34,"2,737",209,...,0,0,12,11,"8,862",662,149,15,"1,088","58,683"
55,50,ท้องถิ่นเขตบางบอน,"46,942",0,4,24,748,10,"1,050",42,...,2,0,31,2,46,400,244,63,"1,746","54,220"

In [ ]:
import pandas as pd
import json
import os
import gc

# 1. กำหนดเส้นทางไฟล์
raw_file_path = "../../data/raw/housing-infomation.csv"
output_file_path = "../../data/interim/bangkok_housing.json"

print("1. ⚙️ กำลังโหลดข้อมูลสิ่งปลูกสร้างจดทะเบียน (ปรับ skiprows=4 เพื่อแก้บั๊ก KeyError)...")
# แก้ไขจาก skiprows=5 เป็น skiprows=4 เพื่อชี้ตำแหน่งไปที่แถว Header หลักของจริงที่มีคำว่า 'ลำดับที่' พอดี
df_raw = pd.read_csv(raw_file_path, skiprows=4)

print("2. 🧹 กำลังทำความสะอาดล้างแถวสรุปยอดและล้างชื่อเขตให้เป็นมาตรฐาน...")
# ลบแถวที่เป็นค่ายอดรวมทั้งหมด (ดักจับจากแถวที่ 'ลำดับที่' เป็นค่าว่าง)
df_filtered = df_raw.dropna(subset=['ลำดับที่']).copy()

# ล้างคำว่า "ท้องถิ่นเขต" ออกให้เหลือแค่คำว่า "เขต..." เพื่อให้ง่ายต่อการนำไป Join เชิงพื้นที่กับ JSON อื่น
df_filtered['จังหวัด/อำเภอ'] = df_filtered['จังหวัด/อำเภอ'].astype(str).str.replace('ท้องถิ่นเขต', 'เขต').str.strip()

print("3. 🔢 แปลงฟีเจอร์ตัวเลข String (ที่มีคอมมา) ให้กลายเป็นประเภท Integer...")
# เลือกสกัดเฉพาะฟีเจอร์สำคัญเชิงธุรกิจทำเลร้านอาหาร/คาเฟ่
target_features = {
    'จังหวัด/อำเภอ': 'district',
    'บ้าน (1)': 'house',
    'ทาวน์เฮ้าส์ (39)': 'townhouse',
    'บ้านแฝด (45)': 'semi_detached_house',
    'อาคารชุด (22)': 'condo',
    'แฟลต (21)': 'flat',
    'หอพัก (14)': 'dormitory',
    'สำนักงาน (20)': 'office',
    'ร้านค้า (19)': 'shop',
    'ตึกแถว (16)': 'shophouse',
    'รวม': 'total_buildings'
}

df_final = pd.DataFrame()

# วนลูปคลีนเครื่องหมายคอมมา "," และแปลงเดต้าเป็นตัวเลขถ้วนๆ ป้องกันปัญหาคณิตศาสตร์พัง
for raw_col, new_col in target_features.items():
    if raw_col in df_filtered.columns:
        if raw_col == 'จังหวัด/อำเภอ':
            df_final[new_col] = df_filtered[raw_col]
        else:
            # ใช้ regex ล้างเครื่องหมายจุลภาคออก และแปลงเป็นค่า Int
            df_final[new_col] = df_filtered[raw_col].astype(str).str.replace(',', '', regex=False).str.strip()
            df_final[new_col] = pd.to_numeric(df_final[new_col], errors='coerce').fillna(0).astype(int)

print("\n--- 📊 🎉 สรุปดัชนีสิ่งปลูกสร้างจดทะเบียนจริงทั่วกรุงเทพฯ ---")
print(f"• จำนวนเขตที่เคลียร์สะอาด: {df_final['district'].nunique()} เขตยุทธศาสตร์ครบถ้วน")
print(f"• ยอดรวมยูนิตอาคารชุด (คอนโด): {df_final['condo'].sum():,} ยูนิต (ทำเลทองคนรุ่นใหม่)")
print(f"• ยอดรวมบ้านแนวราบ (บ้านเดี่ยว+ทาวน์เฮ้าส์): {(df_final['house'].sum() + df_final['townhouse'].sum()):,} หลัง")
print(f"• ยอดรวมพื้นที่สำนักงาน/ออฟฟิศทำงาน: {df_final['office'].sum():,} แห่ง")

# 4. บันทึกเดตาสะอาดก้อนใหม่เข้าคลังสินทรัพย์ปลายทาง
os.makedirs("../../data/interim", exist_ok=True)
df_final.to_json(output_file_path, orient='records', force_ascii=False, indent=4)
print(f"\n💾 🎉 บันทึก Asset ตัวใหม่สำเร็จ! จัดเก็บไฟล์ไว้ที่: {output_file_path}")

# 5. 🧹 สั่ง Garbage Collection เคลียร์ขยะออกจาก RAM ทันที
if 'df_raw' in locals(): del df_raw
if 'df_filtered' in locals(): del df_filtered
if 'df_final' in locals(): del df_final
gc.collect()
print("🤖 [สถานะ: ปลอดภัย 100%] ทำความสะอาดแรมเครื่องเรียบร้อย เบาหวิวพร้อมทำงานต่อครับ!")

1. ⚙️ กำลังโหลดข้อมูลสิ่งปลูกสร้างจดทะเบียน (ปรับ skiprows=4 เพื่อแก้บั๊ก KeyError)...
2. 🧹 กำลังทำความสะอาดล้างแถวสรุปยอดและล้างชื่อเขตให้เป็นมาตรฐาน...
3. 🔢 แปลงฟีเจอร์ตัวเลข String (ที่มีคอมมา) ให้กลายเป็นประเภท Integer...

--- 📊 🎉 สรุปดัชนีสิ่งปลูกสร้างจดทะเบียนจริงทั่วกรุงเทพฯ ---
• จำนวนเขตที่เคลียร์สะอาด: 50 เขตยุทธศาสตร์ครบถ้วน
• ยอดรวมยูนิตอาคารชุด (คอนโด): 889,823 ยูนิต (ทำเลทองคนรุ่นใหม่)
• ยอดรวมบ้านแนวราบ (บ้านเดี่ยว+ทาวน์เฮ้าส์): 2,070,244 หลัง
• ยอดรวมพื้นที่สำนักงาน/ออฟฟิศทำงาน: 10,979 แห่ง

💾 🎉 บันทึก Asset ตัวใหม่สำเร็จ! จัดเก็บไฟล์ไว้ที่: ../cleaned-assets/bangkok_housing_clean.json
🤖 [สถานะ: ปลอดภัย 100%] ทำความสะอาดแรมเครื่องเรียบร้อย เบาหวิวพร้อมทำงานต่อครับ!

,ข้อมูลที่อยู่อาศัยสร้างเสร็จจดทะเบียน เดือน พฤษภาคม 2569,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,การแสดงผลจังหวัด แยกตามอำเภอ (กรุงเทพมหานคร),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ลำดับที่,จังหวัด/อำเภอ,บ้าน (1),โรงแรม (7),โรงงาน (13),หอพัก (14),ตึกแถว (16),ห้องแถว (17),ตึก (18),ร้านค้า (19),...,ห้างหุ้นส่วนจำกัด (33),ห้างหุ้นส่วนนิติบุคคล (34),โกดัง (37),บริษัท (38),ทาวน์เฮ้าส์ (39),บ้านแฝด (45),บ้านแถว (49),ทาวน์โฮม (51),อื่น ๆ,รวม
4,NaN,รวม,"1,969,244","1,778",656,"2,193","52,671","1,057","106,609","12,488",...,23,5,792,558,"101,000","22,662","38,586",765,"107,746","3,373,689"
5,NaN,กรุงเทพมหานคร,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,ท้องถิ่นเขตพระนคร,"16,602",116,0,2,11,0,16,775,...,0,0,0,1,0,0,0,0,697,"18,771"
7,2,ท้องถิ่นเขตดุสิต,"19,570",4,9,6,110,21,431,4,...,0,0,0,1,23,0,0,0,"9,175","34,408"
8,3,ท้องถิ่นเขตหนองจอก,"53,799",1,23,12,774,0,"12,090",250,...,0,0,52,8,"3,154","2,079",506,0,"1,993","76,434"
9,4,ท้องถิ่นเขตบางรัก,"20,250",112,0,4,369,17,"5,236",48,...,0,0,0,0,0,0,0,0,361,"36,130"
10,5,ท้องถิ่นเขตบางเขน,"63,197",71,3,123,"2,423",2,776,837,...,0,0,10,0,"6,415",778,263,0,"13,467","121,263"
11,6,ท้องถิ่นเขตบางกะปิ,"44,794",62,5,0,"4,575",11,"17,104",142,...,0,0,12,0,651,200,896,0,"1,465","119,442"
12,7,ท้องถิ่นเขตปทุมวัน,"14,942",68,1,2,634,20,"4,645",321,...,0,0,0,0,0,2,0,0,707,"32,588"
13,8,ท้องถิ่นเขตป้อมปราบศัตรูพ่าย,"16,693",9,1,2,428,11,53,610,...,0,0,1,3,0,0,0,0,462,"19,644"
14,9,ท้องถิ่นเขตพระโขนง,"20,283",22,29,91,"2,521",9,773,167,...,7,0,13,58,"3,718",83,62,0,"1,360","66,661"
15,10,ท้องถิ่นเขตมีนบุรี,"54,386",15,59,7,732,5,346,32,...,0,2,7,9,"2,374",56,0,0,"1,344","68,688"
16,11,ท้องถิ่นเขตลาดกระบัง,"59,372",29,77,55,460,2,869,299,...,0,0,223,7,"7,797",726,777,84,"3,688","109,969"
17,12,ท้องถิ่นเขตยานนาวา,"31,355",4,7,38,81,33,26,57,...,0,0,37,2,364,80,0,94,"1,028","54,938"
18,13,ท้องถิ่นเขตสัมพันธวงศ์,"11,992",17,0,1,110,1,85,121,...,0,0,0,4,0,0,1,0,153,"12,947"
19,14,ท้องถิ่นเขตพญาไท,"23,675",32,0,13,83,0,286,104,...,0,0,0,10,76,2,0,0,"2,383","47,727"
20,15,ท้องถิ่นเขตธนบุรี,"36,996",6,1,2,"1,465",265,"2,195",62,...,0,0,1,0,19,6,30,0,654,"66,178"
21,16,ท้องถิ่นเขตบางกอกใหญ่,"24,063",10,3,6,236,1,197,20,...,0,0,0,0,244,6,0,0,201,"33,222"
22,17,ท้องถิ่นเขตห้วยขวาง,"48,313",62,1,2,292,0,94,384,...,0,1,3,11,219,96,145,0,"2,535","97,252"
23,18,ท้องถิ่นเขตคลองสาน,"27,296",33,0,6,180,0,110,22,...,0,0,0,0,0,0,0,0,400,"44,647"
24,19,ท้องถิ่นเขตตลิ่งชัน,"38,671",1,2,4,109,1,228,414,...,1,0,5,1,67,64,154,0,"1,780","45,601"
25,20,ท้องถิ่นเขตบางกอกน้อย,"41,979",20,0,35,913,79,112,47,...,0,0,1,0,0,120,364,0,"1,666","57,863"
26,21,ท้องถิ่นเขตบางขุนเทียน,"59,751",6,24,218,"5,627",5,774,383,...,0,0,248,0,"11,078",716,0,82,"2,598","96,674"
27,22,ท้องถิ่นเขตภาษีเจริญ,"39,380",26,0,14,677,11,286,12,...,3,0,0,0,"3,427",173,347,0,884,"70,434"
28,23,ท้องถิ่นเขตหนองแขม,"51,948",1,17,13,688,163,138,45,...,0,0,7,20,"7,105","2,026",34,358,"1,650","66,880"
29,24,ท้องถิ่นเขตราษฎร์บูรณะ,"30,464",9,3,14,258,57,"1,242",80,...,0,0,2,3,294,288,"1,390",0,"2,432","41,022"
30,25,ท้องถิ่นเขตบางพลัด,"38,952",28,31,7,207,13,328,31,...,0,0,0,0,5,4,9,0,"1,042","62,310"
31,26,ท้องถิ่นเขตดินแดง,"34,037",67,6,11,"1,946",10,"2,954",187,...,0,0,1,4,164,16,0,0,"1,154","66,712"
32,27,ท้องถิ่นเขตบึงกุ่ม,"44,715",8,3,6,"2,144",8,"8,805",24,...,0,0,4,2,877,391,729,0,"1,571","80,450"
33,28,ท้องถิ่นเขตสาทร,"28,176",59,4,4,84,3,757,37,...,0,0,2,0,1,0,3,0,"1,940","45,286"
34,29,ท้องถิ่นเขตบางซื่อ,"39,222",1,3,116,545,7,243,225,...,0,0,5,1,370,2,7,0,"2,717","79,322"
35,30,ท้องถิ่นเขตจตุจักร,"59,920",54,2,477,"1,215",0,27,969,...,0,0,0,2,41,179,747,0,"2,528","143,255"
36,31,ท้องถิ่นเขตบางคอแหลม,"30,412",8,2,16,320,0,"1,397",26,...,0,0,0,0,25,6,29,0,666,"41,122"
37,32,ท้องถิ่นเขตประเวศ,"50,899",27,12,25,"1,848",22,"1,694",102,...,6,0,15,285,"5,226","2,242","7,629",0,"3,471","108,495"
38,33,ท้องถิ่นเขตคลองเตย,"43,047",130,22,15,203,5,158,28,...,0,0,0,0,1,2,0,0,"3,034","83,912"
39,34,ท้องถิ่นเขตสวนหลวง,"31,992",16,2,11,898,12,"17,896",29,...,0,0,0,2,481,555,"3,410",22,765,"89,633"
40,35,ท้องถิ่นเขตจอมทอง,"59,775",5,6,10,490,6,324,63,...,0,2,11,10,490,167,"1,420",0,"1,308","74,988"
41,36,ท้องถิ่นเขตดอนเมือง,"48,232",14,4,64,949,4,297,53,...,0,0,0,6,"11,257","1,787",4,15,"2,089","84,166"
42,37,ท้องถิ่นเขตราชเทวี,"22,824",235,0,108,"1,380",17,"1,586","2,248",...,0,0,3,0,0,2,0,0,"3,355","58,118"
43,38,ท้องถิ่นเขตลาดพร้าว,"43,189",54,0,0,929,1,431,77,...,0,0,6,5,"2,058",321,169,0,"1,247","60,963"
44,39,ท้องถิ่นเขตวัฒนา,"39,092",210,2,13,486,13,990,196,...,0,0,0,1,27,0,0,0,612,"88,103"
45,40,ท้องถิ่นเขตบางแค,"83,579",4,4,32,253,4,649,86,...,0,0,3,0,"5,084",416,"1,391",0,788,"100,335"
46,41,ท้องถิ่นเขตหลักสี่,"32,758",26,16,111,"1,113",22,38,132,...,1,0,11,40,"1,127",371,989,0,"6,413","63,342"
47,42,ท้องถิ่นเขตสายไหม,"66,335",2,1,117,"5,115",64,"6,504",99,...,0,0,1,4,"5,785","1,529","7,507",12,"6,680","113,268"
48,43,ท้องถิ่นเขตคันนายาว,"26,376",9,16,102,"1,746",5,"2,882",224,...,1,0,0,15,"2,019",362,985,0,956,"49,594"
49,44,ท้องถิ่นเขตสะพานสูง,"31,255",4,2,14,"1,176",7,"1,700",36,...,2,0,20,10,"2,530","1,024","4,475",0,775,"44,941"
50,45,ท้องถิ่นเขตวังทองหลาง,"45,498",25,2,1,"2,233",2,"2,924",131,...,0,0,1,9,214,315,764,0,944,"66,667"
51,46,ท้องถิ่นเขตคลองสามวา,"72,043",1,18,17,"1,277",56,149,"1,394",...,0,0,18,10,"6,597","4,018","2,913",20,"5,291","95,430"
52,47,ท้องถิ่นเขตบางนา,"29,688",55,202,43,396,18,693,161,...,0,0,20,1,251,29,44,0,"1,507","83,304"
53,48,ท้องถิ่นเขตทวีวัฒนา,"33,910",0,3,43,134,0,"1,284",443,...,0,0,6,0,437,361,0,0,976,"37,687"
54,49,ท้องถิ่นเขตทุ่งครุ,"36,605",0,24,136,"1,080",34,"2,737",209,...,0,0,12,11,"8,862",662,149,15,"1,088","58,683"
55,50,ท้องถิ่นเขตบางบอน,"46,942",0,4,24,748,10,"1,050",42,...,2,0,31,2,46,400,244,63,"1,746","54,220"