In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../../data/raw/bts.csv', encoding='latin-1')
df

         _id    No.       Date     Organization Number_Passenger Note
0          1      1  1/10/2022              SRT           52,584  NaN
1          2      2  1/10/2022              ARL           46,393  NaN
2          3      3  1/10/2022         Red Line           12,558  NaN
3          4      4  1/10/2022    MRT Blue Line          221,452  NaN
4          5      5  1/10/2022  MRT Purple Line           24,843  NaN
...      ...    ...        ...              ...              ...  ...
11655  11656  11656    30/6/26  MRT Purple Line            81654  NaN
11656  11657  11657    30/6/26  MRT Yellow Line            54735  NaN
11657  11658  11658    30/6/26    MRT Pink Line            80121  NaN
11658  11659  11659    30/6/26   BTS Green Line           762811  NaN
11659  11660  11660    30/6/26    BTS Gold Line             6984  NaN

[11660 rows x 6 columns]

In [4]:
df.drop(columns=["Note", "_id", 'No.'], inplace=True)
df

            Date     Organization Number_Passenger
0      1/10/2022              SRT           52,584
1      1/10/2022              ARL           46,393
2      1/10/2022         Red Line           12,558
3      1/10/2022    MRT Blue Line          221,452
4      1/10/2022  MRT Purple Line           24,843
...          ...              ...              ...
11655    30/6/26  MRT Purple Line            81654
11656    30/6/26  MRT Yellow Line            54735
11657    30/6/26    MRT Pink Line            80121
11658    30/6/26   BTS Green Line           762811
11659    30/6/26    BTS Gold Line             6984

[11660 rows x 3 columns]

In [5]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed", dayfirst=True)
df = df.rename(columns={
    "Date": "date",
    "Organization": "organization",
    "Number_Passenger": "passenger_count"
})

In [6]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["weekday"] = df["date"].dt.dayofweek
df["is_weekend"] = df["weekday"] >= 5

df

,date,organization,passenger_count,year,month,day,weekday,is_weekend
0,2022-10-01,SRT,"52,584",2022,10,1,5,True
1,2022-10-01,ARL,"46,393",2022,10,1,5,True
2,2022-10-01,Red Line,"12,558",2022,10,1,5,True
3,2022-10-01,MRT Blue Line,"221,452",2022,10,1,5,True
4,2022-10-01,MRT Purple Line,"24,843",2022,10,1,5,True
...,...,...,...,...,...,...,...,...
11655,2026-06-30,MRT Purple Line,81654,2026,6,30,1,False
11656,2026-06-30,MRT Yellow Line,54735,2026,6,30,1,False
11657,2026-06-30,MRT Pink Line,80121,2026,6,30,1,False
11658,2026-06-30,BTS Green Line,762811,2026,6,30,1,False
11659,2026-06-30,BTS Gold Line,6984,2026,6,30,1,False

In [7]:
df.to_csv("../../data/processed/bts_clean.csv", index=False)